### ISSUE TITLE
Questions about clustering

### ISSUE THREAD

**Issue by willros** [cytham/telomap#1]
Hi,

I have read your paper and have looked at the Telomap package that you have provided – thank you for this interesting piece of work!

Sorry for opening a issue , but I did not know how to reach out to you in another way.

I have some questions regarding the clustering of subtelomeric regions and wondered if you possible could answer some of them? 

I would really appreciate it! 

Regards,
William

**Comment by cytham** [comment]
Hi William,

Thank you for your interest in our work.

I have contacted you through email so I will close this for now.

cy
