### ISSUE TITLE
Command line interpretation - capture_oligo.fa and barcodes.fa files

### ISSUE THREAD

**Issue by Alwaysmihe** [cytham/telomap#3]
Hi there,

Thanks for creating this wonderful tool. 

I have some questions about the command line. According to the published paper (doi: 10.1038/s41467-023-35823-7.), capture_oligo.fa and barcodes.fa files are generated through the packages within the requirement of Telomap installation. Could you please provide more information about how to get these two files ahead to put into the command line? 

As I assumed Telomap itself would have the packages to generate capture_oligo.fa and barcodes.fa files, I left the capture_oligo.fa and barcodes.fa blank in the command line,

`$telomap $bam pacbio-bam 8 $output`

and here is the error.

`Traceback (most recent call last):
  File "telomap", line 116, in <module>
    main()
  File "telomap", line 27, in main
    cores = argv[5]
IndexError: list index out of range`

Thanks a lot.

**Comment by cytham** [comment]
Hi @Alwaysmihe, capture_oligo.fa and barcodes.fa are mandatory files for Telomap to work, and they are not generated automatically within Telomap but have to be supplied by the user. 
May I know how your telomere data was generated? Was it through sequence capture as described in the paper? These fasta files should contain the capture oligo and barcode sequences used during the telomere capturing wet-lab step.

**Comment by Alwaysmihe** [comment]
Hi @cytham,

Thanks for your reply. We generated the pacbio data of the whole genomes not telomere-specific. Therefore, we may not have the oligo and telobaits data as no wet-lab telomere length measurements or telomere-related manipulations have been performed. If I understand correctly, we could not use Telomap without capture_oligo.fa and barcodes.fa files which were created in the wet-lab before pacbio data generation by the manufacturer.

**Comment by cytham** [comment]
Just to clarify, the capture_oligo.fa and barcodes.fa files need to be created by the user according to the oligos/barcodes used during the wet lab telobait capture procedure. Currently, Telomap cannot run without these files, but let me look into it and try to provide a way to run for whole genome data. However, do note that the number of reads with telomeres are expected to be low.

**Comment by Alwaysmihe** [comment]
Thank you for the clarification. The design of telomap is excellent and well explained in the paper. Our team is based on bioinformatics than laboratory work, and therefore, it would be fantastic for us to run telomap without these files. But don't concern too much if it is challenging.

**Comment by cytham** [comment]
Hi @Alwaysmihe, I am happy to let you know that you can now run telomap (v0.1.0) without the oligo or barcode files. You will just have to use WGS long-read data as input. Feel free to try it. Thanks
