### ISSUE TITLE
length of barcode in capture.py

### ISSUE THREAD

**Issue by choudharis2** [cytham/telomap#4]
Hi,

Thank you for this wonderful application and tool for measuring the length of Telomers.
We are trying to utilize this tool to analyze our data generated by the protocol defined in the paper.

We are getting an error from capture.py script:

`Exception: Error: Barcode sequence >S2 does not match`

After checking the script we found that the barcode length defined in the code is 13

```
if fasta[end - 13:end] != self.barcodes[barcode][1]:
if fasta[junction:junction + 13] != self.barcodes[barcode][0]:
```
We changed the code as below and it is not giving error any more.

```
if fasta[end - 8:end] != self.barcodes[barcode][1]:
if fasta[junction:junction + 8] != self.barcodes[barcode][0]:
```

Could you let us know if changing the value is correct and what it the reason you have used 13.

Moreover the analysis run without an error after changing the value to 8 but many columns in the telomap.tsv are empty:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/choudharis2/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/choudharis2/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

#RNAME | BARCODE | STRAND | CHROM | RLEN | TELOMERE_LEN | TELOMERE_M_LEN | TRF_COUNT | TELOMERE_END | MOTIF | START_JUNCT | BARCODE_JUNC | OLIGO | OLIGO_SCORE | BARCODE_SCORE | NUM_PASS | RQUAL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ccs | S1 | + |   | 5672 |   |   |   | GATCGA |   |   | 5639 | A1 | 38 | 8 | 27 | 1

</body>

</html>

Thanks in advance.

**Comment by cytham** [comment]
Hi @choudharis2, thanks for using telomap.

Thanks for raising this, this is likely a bug. 13 is used because it was the length of the barcode I used in the paper. I will change this value to the length of the barcode in the next version. Meanwhile, changing it to 8 (which should be the length of your barcode) should work just fine.

The rows with empty values are reads that did not pass the telomere detection and likely have no telomeric sequences. As you can see, the end of the read that is next to the barcode has the motif "GATCGA" which is not a telomeric repeat. Do you find any other rows that has fully filled values? These are the reads with telomeres.

**Comment by choudharis2** [comment]
Hi @cytham , thank you for the reply.

After checking the file I did find few reads that have filled values, but the number is very low. Only 0.099% of the reads have values. Does this sound okay?  

Additionally, I am getting an error from the plot.py script
```
plots.py", line 489, in plot_chrm_bar
    sort_chrm = natsorted(dfa[dfa['sample'] == s]['chrm'].tolist(), alg=ns.LOWERCASEFIRST)
    raise KeyError(key) from err
KeyError: 'chrm'
```

Can you please have a look.

Thanks

**Comment by cytham** [comment]
@choudharis2 This is a bug. Thanks for raising this. I have fixed it and released a new version v0.0.5. I have also fixed the "Barcode sequence match" bug. Please try it and let me know. Thanks

Regarding the low reads with values (i.e. low number of telomeric reads), this should be due to inefficient capturing of telomeres before sequencing. May I know how you performed the telomere capture?

**Comment by choudharis2** [comment]
Thank you @cytham for checking the error.
We have utilized the same protocol as given in the paper.

I would like to bring few other issues that I encounter while running the code. 
```
  File "/tvs.py", line 71, in tvs_analyzer
    tvs_arr[b][c] = arr_sum
UnboundLocalError: local variable 'arr_sum' referenced before assignment
```

I am not sure if there is an indentation error  above or this is something to do with my data as I have one sequence found in the` anchors.tsv f`ile.  If I fix the indentation I can run the code without any error.
Although when I used one of the fastq file from your data I am not getting this error. So, I believe this is something to do with my data. Could tell me how to bypass this error. 

```

telomap", line 111, in create_tsv
    df.to_csv(df_tsv, mode='a', header=False, index=False, sep='\t')
  ValueError: I/O operation on closed file.
```
I had a quick fix for this in my download version but maybe you want to check this.

After fixing these issues I was able to run the code without any error, but I am not getting any plots in `plots_tvs` and` plots_trf`.

Please let me know your comments.

Thanks for your time.

**Comment by cytham** [comment]
Hi @choudharis2, thanks for raising the issues, they are very helpful. I have fixed them in v0.06, please try again if you have the time. Do let me know if you find more bugs, thanks!

I have also included an example on the capture oligo and barcode FASTA file creation on the README, FYI.

**Comment by choudharis2** [comment]
Hi @cytham, thank you for fixing the issues. I was able to run the pipeline without an issue.
But I want to bring your attention to the results, I used one of the fastq files given in the paper. This time I see the last two columns were empty which was not the case in the past. This information is from the fastq file and wondering why these are not getting filled up. See table below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/choudharis2/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/choudharis2/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


#RNAME | BARCODE | STRAND | CHROM | RLEN | TELOMERE_LEN | TELOMERE_M_LEN | TRF_COUNT | TELOMERE_END | MOTIF | START_JUNCT | BARCODE_JUNC | OLIGO | OLIGO_SCORE | BARCODE_SCORE | NUM_PASS | RQUAL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ERR9118754.1056 | S1 | - | chr9q/chr10q | 1587 | 1432 | 768 |   | TATCGA | TTAGGG | 122 | 1554 | A1 | 38 | 8 |   |  
ERR9118754.40 | S1 | + | U4 | 2291 | 1653 | 1344 | 81 | GATCGA | TTAGGG | 605 | 2258 | A1 | 38 | 8 |   |  
ERR9118754.945 | S1 | - |   | 1924 | 1693 | 1590 | 77 | GATCGA | TTAGGG | 198 | 1891 | A1 | 38 | 8 |   |  
ERR9118754.688 | S1 | + |   | 2856 | 1769 | 1320 | 76 | GATCGA | TTAGGG | 1054 | 2823 | A1 | 38 | 8 |   |  
ERR9118754.797 | S1 | - | U4 | 3678 | 1773 | 1608 | 81 | GATCGA | TTAGGG | 1872 | 3645 | A1 | 38 | 8 |   |  



</body>

</html>


Furthermore, I have another question about the `CHROM` column, I understand if there is not a hit from the ref the letter `U` gets filled in, I wonder why there are many telomere reads that have this column empty. For example in the above table, these two reads have telomere but the CHROM column is not filled (ERR9118754.945
ERR9118754.688)

Please can you help me clarify these results.

The `plots_tvs` and `plots_trf `were empty and I checked that code is commented in the telomap. You want to check this, for my analysis I uncommented these two lines.
```
    #plot_trf_boxplot(out.barcode_reads, out.df, trf_dir)

    # Plot TVS figures
    # Plot TVS signature figures
    #plot_tvs_sig(out.tvs_arr, out.tvs_read_counts, tsv_dir, telo_len=1000) 
```

Thanks again for your time and help.

**Comment by cytham** [comment]
Hi @choudharis2,

Last two columns get the info from PacBio BAM input.  Since the input is FASTQ, last two columns are expected to be blank.

Telomeric reads with `U` assigned in the `CHROM` column means that its subtelomeric region belongs to a subtelomeric cluster in your dataset (e.g. U4) but did not get a confident hit on any chromosomal end. Telomeric reads with blank `CHROM` column means that its subtelomeric region did not belong to any subtelomeric cluster in your dataset.

Thanks for pointing out the commented tvs and trf plots. I'll uncomment them in the next version. Did it run successfully after uncommenting? Thanks!

**Comment by choudharis2** [comment]
Hi @cytham, thank you for the clarification. Yes I was able to run without an error after uncommenting those line.

Thanks again for all the help.

**Comment by cytham** [comment]
Hi @choudharis2, I would like to let you know that telomap (v0.1.0) can now run on WGS long-read data. I have also added more descriptions regarding the output files in the README. Hope its clearer now. Feel free to try the latest version. I'll close this thread for now.

**Comment by choudharis2** [comment]
> Hi @choudharis2, I would like to let you know that telomap (v0.1.0) can now run on WGS long-read data. I have also added more descriptions regarding the output files in the README. Hope its clearer now. Feel free to try the latest version. I'll close this thread for now.

Thanks! The WGS version worked without an issue.
