### ISSUE TITLE
recursion error

### ISSUE THREAD

**Issue by bio-tombow** [cytham/telomap#7]
Hi there,
I use telomap but somthing wrong, here is my command
        telomap test.bam capture_oligo.fa barcodes1.fa pacbio-bam 40 ./
my capter_oliga.fa:
>capture_oligo
GATGCCAGATGCACGGAGCA

my barcodes1.fa
>sample1
ATCGACGGTTCAA
>sample2
ATCGAGCTGGATT
>sample3
ATCGATAACTCGG

and no additional "\n" at the end of these file.
but this error occured,
![65Q`2)H3%MU3DFB% XV 0(X](https://github.com/cytham/telomap/assets/52068033/2d3dc86d-e552-4c31-905c-efff1e58ab7d)
Please help ME,
Qing

**Comment by cytham** [comment]
Hi @bio-tombow, may I know what version of telomap are you running? And what python and pandas versions are you using?

**Comment by bio-tombow** [comment]
0.0.7

**Comment by cytham** [comment]
What's your python and pandas versions? Can you try the latest version 0.1.0 please?

**Comment by bio-tombow** [comment]
you mean Telomap version 0.1.0? ok i will try

**Comment by bio-tombow** [comment]
my pandas version is 1.5, and i updated it to 2.2.1, then the problem is solved! 3Q~~

**Comment by cytham** [comment]
awesome!
